# Generated by Django 5.2.7 on 2025-10-18 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_filter', '0002_album_added_at_album_popularity_album_release_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='albums',
        ),
        migrations.AddField(
            model_name='album',
            name='album_cover',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='artists',
            field=models.ManyToManyField(related_name='albums', to='spotify_filter.artist'),
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('track_number', models.IntegerField()),
                ('duration_ms', models.IntegerField()),
                ('preview_url', models.URLField(blank=True, max_length=500, null=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify_filter.album')),
            ],
        ),
    ]
