# Generated by Django 5.2.7 on 2025-10-18 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_filter', '0003_remove_artist_albums_album_album_cover_album_artists_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='spotify_id',
            field=models.CharField(max_length=50),
        ),
    ]
