# Generated by Django 5.2.7 on 2025-10-18 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_filter', '0005_alter_artist_spotify_id_alter_track_spotify_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='album',
        ),
        migrations.AddField(
            model_name='track',
            name='albums',
            field=models.ManyToManyField(related_name='tracks', to='spotify_filter.album'),
        ),
    ]
